[GENERAL]
run_engine=openfpga_shell
power_tech_file = /home/ketan/OpenFPGA/openfpga_flow/tech/PTM_45nm/45nm.xml
power_analysis = true
spice_output=false
verilog_output=true
timeout_each_job = 20*60
fpga_flow=vpr_blif

[OpenFPGA_SHELL]
openfpga_shell_template=/home/ketan/OpenFPGA/openfpga_flow/tasks/ketan/scripts/generate_fabric.openfpga
openfpga_arch_file=/home/ketan/OpenFPGA/openfpga_flow/tasks/ketan/arch/k4_N4_40nm_cc_openfpga.xml
openfpga_sim_setting_file=/home/ketan/OpenFPGA/openfpga_flow/tasks/ketan/sim/auto_sim_openfpga.xml
openfpga_verilog_output_dir=/home/ketan/OpenFPGA/openfpga_flow/tasks/ketan/latest/k4_N4_tileable_40nm/and2/MIN_ROUTE_CHAN_WIDTH
openfpga_vpr_device_layout=2x2
openfpga_vpr_route_chan_width=20

[ARCHITECTURES]
arch0=/home/ketan/OpenFPGA/openfpga_flow/tasks/ketan/arch/k4_N4_tileable_40nm.xml

[BENCHMARKS]
bench0=/home/ketan/OpenFPGA/openfpga_flow/tasks/ketan/benchmarks/and2/and2.blif

[SYNTHESIS_PARAM]
bench0_top = and2
bench0_act = /home/ketan/OpenFPGA/openfpga_flow/tasks/ketan/benchmarks/and2/and2.act
bench0_verilog = /home/ketan/OpenFPGA/openfpga_flow/tasks/ketan/benchmarks/and2/and2.v

[SCRIPT_PARAM_MIN_ROUTE_CHAN_WIDTH]
